name: Docker Actions

on:
  pull_request:
    types: [open, labeled]
    branches: [test]
  push:
    branches: [master, action-three]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: meow
        uses: ./.github/actions/cat-facts
      
      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          catFact: ${{steps.cat.outputs.fact}}
          issueTitle: "a cat fact for you"
